name: Quad_embeds
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.1
  - numpy=1.19.2
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=11.1.1
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - tqdm=4.62.3
  - scikit-image=0.18.1
  - scikit-learn=0.23.2
  - scikit-video=1.1.11
  - scipy=1.5.0
  - h5py=2.10.0
